{ mkDerivation, base, bytestring, containers, glib, lib, text }:
mkDerivation {
  pname = "haskell-gi-base";
  version = "0.20.1";
  sha256 = "e9d8d3d75e0ea91108339daa172bc938512432509caeafdf5bd96551a380f046";
  revision = "1";
  editedCabalFile = "0c6w8igqbc3a3ywng9872b12ipdg1y8xypi5plzrpws8sii74cki";
  libraryHaskellDepends = [ base bytestring containers text ];
  libraryPkgconfigDepends = [ glib ];
  homepage = "https://github.com/haskell-gi/haskell-gi-base";
  description = "Foundation for libraries generated by haskell-gi";
  license = lib.licenses.lgpl21Only;
}
