{ mkDerivation, base, bytestring, containers, glib, lib, text }:
mkDerivation {
  pname = "haskell-gi-base";
  version = "0.22.0";
  sha256 = "5881220bc41862e88b1541f29376e13c96613adceaf0bf85922f1ae22586910e";
  libraryHaskellDepends = [ base bytestring containers text ];
  libraryPkgconfigDepends = [ glib ];
  homepage = "https://github.com/haskell-gi/haskell-gi-base";
  description = "Foundation for libraries generated by haskell-gi";
  license = lib.licenses.lgpl21Only;
}
