{ mkDerivation, aterm, base, lib, mtl, transformers, wl-pprint }:
mkDerivation {
  pname = "aterm-utils";
  version = "0.2.0.2";
  sha256 = "40ce898c1159d27c2bc6cf20100d57736afc6ae9a0d81a208740d1dc5b15d37b";
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [ aterm base mtl transformers wl-pprint ];
  executableHaskellDepends = [ aterm base transformers wl-pprint ];
  homepage = "https://github.com/GaloisInc/aterm-utils";
  description = "Utility functions for working with aterms as generated by Minitermite";
  license = lib.licenses.bsd3;
  mainProgram = "ppaterm";
}
