{ mkDerivation, aterm, base, lib, transformers, wl-pprint }:
mkDerivation {
  pname = "aterm-utils";
  version = "0.1.0.0";
  sha256 = "1abe4f3cd20e2e56661425a9bca89023f0e871dc938b12d4fdcc32409035fad0";
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [ aterm base transformers wl-pprint ];
  executableHaskellDepends = [ aterm base transformers wl-pprint ];
  homepage = "https://github.com/GaloisInc/aterm-utils";
  description = "Utility functions for working with aterms as generated by Minitermite";
  license = lib.licenses.bsd3;
  mainProgram = "ppaterm";
}
