{ mkDerivation, base, bytestring, containers, glib, lib, text }:
mkDerivation {
  pname = "haskell-gi-base";
  version = "0.14";
  sha256 = "97e3faae862d70371405b3c324329b58c5d9be055a08daf759da86cb4463567a";
  revision = "1";
  editedCabalFile = "169565bcy34i1dxhyphvm7rahv3vmbk9pgr598wfpqsqahydcza4";
  libraryHaskellDepends = [ base bytestring containers text ];
  libraryPkgconfigDepends = [ glib ];
  homepage = "https://github.com/haskell-gi/haskell-gi-base";
  description = "Foundation for libraries generated by haskell-gi";
  license = lib.licenses.lgpl21Only;
}
