{ mkDerivation, base, bytestring, containers, glib, lib
, optics-core, text
}:
mkDerivation {
  pname = "haskell-gi-base";
  version = "0.26.9";
  sha256 = "c359bbcfb06928f6b9817d4fb8f44b595382a7d405b63c2ceefed85f26c221d2";
  libraryHaskellDepends = [
    base bytestring containers optics-core text
  ];
  libraryPkgconfigDepends = [ glib ];
  homepage = "https://github.com/haskell-gi/haskell-gi";
  description = "Foundation for libraries generated by haskell-gi";
  license = lib.licenses.lgpl21Only;
}
