{ mkDerivation, base, bytestring, containers, fin, lib, primitive
, record-hasfield, sdl3, some, template-haskell, vec, vector
}:
mkDerivation {
  pname = "sdl3-bindgen-sys";
  version = "0.0.0.2";
  sha256 = "15174d3e341740354fb5174dab3ab4b97e07e5a1d08a351e95694ec108f44453";
  libraryHaskellDepends = [
    base bytestring containers fin primitive record-hasfield some
    template-haskell vec vector
  ];
  libraryPkgconfigDepends = [ sdl3 ];
  doHaddock = false;
  homepage = "https://github.com/jtnuttall/lithon#readme";
  description = "Complete SDL3 bindings, raw + curated, generated by hs-bindgen";
  license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
}
