{ mkDerivation, base, bytestring, containers, glib, lib, text }:
mkDerivation {
  pname = "haskell-gi-base";
  version = "0.13";
  sha256 = "57c33125b0fac446007b7cc6ea5d0d853bcdf725cdca8028c879561d977d0363";
  revision = "1";
  editedCabalFile = "17qzjlqbcs9k53s37cbhr0x9n77bcjxmx7k43ksgrvn89vzqpkn1";
  libraryHaskellDepends = [ base bytestring containers text ];
  libraryPkgconfigDepends = [ glib ];
  homepage = "https://github.com/haskell-gi/haskell-gi-base";
  description = "Foundation for libraries generated by haskell-gi";
  license = lib.licenses.lgpl21Only;
}
