{ mkDerivation, base, casadi, casadi-bindings-internal, lib, vector
}:
mkDerivation {
  pname = "casadi-bindings-core";
  version = "2.3.0.1";
  sha256 = "a770ccd0491f1d0eab06bd03b36115122a781e4106906a8489d18d85d7a8ff29";
  libraryHaskellDepends = [ base casadi-bindings-internal vector ];
  libraryPkgconfigDepends = [ casadi ];
  description = "autogenerated low level bindings to casadi";
  license = lib.licenses.lgpl3Only;
}
