{ mkDerivation, base, bytestring, containers, glib, lib, text }:
mkDerivation {
  pname = "haskell-gi-base";
  version = "0.19";
  sha256 = "ff3241d123a03e486ea0b6cb10b36262bfcd90411ac19859aa5c08f60dfe2af9";
  revision = "1";
  editedCabalFile = "0hi5ng6i8kn61w3mz71vkw06m1rdgk3rzah97g2v44ms8k0kv6hl";
  libraryHaskellDepends = [ base bytestring containers text ];
  libraryPkgconfigDepends = [ glib ];
  homepage = "https://github.com/haskell-gi/haskell-gi-base";
  description = "Foundation for libraries generated by haskell-gi";
  license = lib.licenses.lgpl21Only;
}
