{ mkDerivation, base, bytestring, containers, glib, lib, text }:
mkDerivation {
  pname = "haskell-gi-base";
  version = "0.18.3";
  sha256 = "20b9765915b9007fdf6a35cca1acd8112582d3a7dd319a270ce583c7de6520b0";
  revision = "1";
  editedCabalFile = "1xd36189ag2w4wnk4x12l468spkhb64qpmwxq3pfawpjpi3w7n8d";
  libraryHaskellDepends = [ base bytestring containers text ];
  libraryPkgconfigDepends = [ glib ];
  homepage = "https://github.com/haskell-gi/haskell-gi-base";
  description = "Foundation for libraries generated by haskell-gi";
  license = lib.licenses.lgpl21Only;
}
