{ mkDerivation, base, bytestring, containers, glib, lib, text }:
mkDerivation {
  pname = "haskell-gi-base";
  version = "0.20.2";
  sha256 = "e7ee6b5061acb06412fe321b9cb8a2c7dd31eaf8689577ae762a0ab9e7185916";
  revision = "1";
  editedCabalFile = "01gswkvx4z1h1a4j8xl4i3p2bgk4c6bj5ba0izlr6krf9hy54pab";
  libraryHaskellDepends = [ base bytestring containers text ];
  libraryPkgconfigDepends = [ glib ];
  homepage = "https://github.com/haskell-gi/haskell-gi-base";
  description = "Foundation for libraries generated by haskell-gi";
  license = lib.licenses.lgpl21Only;
}
