{ mkDerivation, array, base, bytestring, half, lib, monad-control
, mtl, text, transformers-base
}:
mkDerivation {
  pname = "futhask-base";
  version = "0.1.0.0";
  sha256 = "f0a519f12d451ece7ecccabaaef2bcf63b5634cc049b870073a184270255a64f";
  libraryHaskellDepends = [
    array base bytestring half monad-control mtl text transformers-base
  ];
  homepage = "https://gitlab.com/Gusten_Isfeldt/futhask#readme";
  description = "Base library for libraries generated by futhask";
  license = lib.licenses.bsd3;
}
