{ mkDerivation, base, lib, protocol-buffers
, protocol-buffers-descriptor
}:
mkDerivation {
  pname = "gtfs-realtime";
  version = "0.1.0.0";
  sha256 = "73fe507995528849738b307c5be8598e1b504c1f483f77fe26b1918432f7a763";
  revision = "1";
  editedCabalFile = "0i54m5khs4qcca1wyyzi06q9pqs0m0cnbrzwxv2mwilx3figdl7c";
  libraryHaskellDepends = [
    base protocol-buffers protocol-buffers-descriptor
  ];
  homepage = "https://github.com/CthulhuDen/gtfs-realtime#readme";
  description = "GTFS RealTime protobafs library (autogenerated from .proto file)";
  license = lib.licenses.bsd3;
}
