{ mkDerivation, base, lib, protocol-buffers
, protocol-buffers-descriptor
}:
mkDerivation {
  pname = "gtfs-realtime";
  version = "0.2.0.0";
  sha256 = "8042e96df50ffe72a9df967789eb2383a6acd5821dca8631e79a253d5119b179";
  libraryHaskellDepends = [
    base protocol-buffers protocol-buffers-descriptor
  ];
  homepage = "https://github.com/CthulhuDen/gtfs-realtime#readme";
  description = "GTFS RealTime protobafs library (autogenerated from .proto file)";
  license = lib.licenses.bsd3;
}
