{ mkDerivation, base, bytestring, containers, glib, lib, text }:
mkDerivation {
  pname = "haskell-gi-base";
  version = "0.25.0";
  sha256 = "1e57c4e132c67995f3a299493fd69e5d7b801323374452e44e232783ab320e90";
  revision = "1";
  editedCabalFile = "1pl2mzjdsnvvkfmr622jvw2vk9gxdql5flck4vb60nr9d970zg9r";
  libraryHaskellDepends = [ base bytestring containers text ];
  libraryPkgconfigDepends = [ glib ];
  homepage = "https://github.com/haskell-gi/haskell-gi";
  description = "Foundation for libraries generated by haskell-gi";
  license = lib.licenses.lgpl21Only;
}
