{ mkDerivation, base, bytestring, containers, glib, lib, text }:
mkDerivation {
  pname = "haskell-gi-base";
  version = "0.15";
  sha256 = "b7c622d428fe2369f20dfba9a02fd9d29366ab9a3949a22486d46a4abf70bb37";
  revision = "1";
  editedCabalFile = "1xi18wsqhdsj93nns1gv6ilqp8w1vlqdklhvf7dbl932x4p09dpx";
  libraryHaskellDepends = [ base bytestring containers text ];
  libraryPkgconfigDepends = [ glib ];
  homepage = "https://github.com/haskell-gi/haskell-gi-base";
  description = "Foundation for libraries generated by haskell-gi";
  license = lib.licenses.lgpl21Only;
}
