{ mkDerivation, aeson, base, base64-bytestring, bytestring, lib
, text, time
}:
mkDerivation {
  pname = "typed-wire-utils";
  version = "0.1.0.0";
  sha256 = "26edf29617e27d569f4e44d88b0aadc7d028476ae5eb9dbabbb7c605a71ab230";
  libraryHaskellDepends = [
    aeson base base64-bytestring bytestring text time
  ];
  homepage = "http://github.com/typed-wire/hs-typed-wire-utils#readme";
  description = "Haskell utility library required for code generated by typed-wire compiler";
  license = lib.licenses.bsd3;
}
