{ mkDerivation, base, casadi, casadi-bindings-internal, containers
, lib, vector
}:
mkDerivation {
  pname = "casadi-bindings-core";
  version = "2.4.1.0";
  sha256 = "f35fdfc2d8d33c5455d3e7dccce341332c0620db0445f99386f1e7920e053b6c";
  libraryHaskellDepends = [
    base casadi-bindings-internal containers vector
  ];
  libraryPkgconfigDepends = [ casadi ];
  description = "autogenerated low level bindings to casadi";
  license = lib.licenses.lgpl3Only;
}
