{ mkDerivation, base, bytestring, containers, glib, lib, text }:
mkDerivation {
  pname = "haskell-gi-base";
  version = "0.18";
  sha256 = "ebf2f2a9845ca90a50bdf1c0943d47fa55bade1d622d5f5e75ba98cd097ff94c";
  revision = "1";
  editedCabalFile = "00x76sgl2iq5fx4m24wqzsmp2iyp0374fabiqjjlyr94a6llnpi7";
  libraryHaskellDepends = [ base bytestring containers text ];
  libraryPkgconfigDepends = [ glib ];
  homepage = "https://github.com/haskell-gi/haskell-gi-base";
  description = "Foundation for libraries generated by haskell-gi";
  license = lib.licenses.lgpl21Only;
}
