{ mkDerivation, ALUT, base, lib }:
mkDerivation {
  pname = "turing-music";
  version = "0.1.1";
  sha256 = "c3cfcf66e1fbf3a75488d1ce35bead220f70921eed0dc6b3a846f728f77b6e98";
  isLibrary = false;
  isExecutable = true;
  executableHaskellDepends = [ ALUT base ];
  description = "Plays music generated by Turing machines with 5 states and 2 symbols";
  license = lib.licenses.bsd3;
  mainProgram = "turing-music";
}
