{ mkDerivation, aterm, base, lib, mtl, transformers, wl-pprint }:
mkDerivation {
  pname = "aterm-utils";
  version = "0.2.0.1";
  sha256 = "1770d0d35cee1924b3c49ea5ea54e8512674ae6dfc553aa10ec30ede69a75c86";
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [ aterm base mtl transformers wl-pprint ];
  executableHaskellDepends = [ aterm base transformers wl-pprint ];
  homepage = "https://github.com/GaloisInc/aterm-utils";
  description = "Utility functions for working with aterms as generated by Minitermite";
  license = lib.licenses.bsd3;
  mainProgram = "ppaterm";
}
