{ mkDerivation, ALUT, base, lib }:
mkDerivation {
  pname = "turing-music";
  version = "0.1";
  sha256 = "24674f26c3dceb1bd6a748f929456d8590e7d480755470bedb121f6b37b2e5d1";
  isLibrary = false;
  isExecutable = true;
  executableHaskellDepends = [ ALUT base ];
  description = "Plays music generated by Turing machines with 5 states and 2 symbols";
  license = lib.licenses.bsd3;
  mainProgram = "turing-music";
}
