{ mkDerivation, base, bytestring, containers, fin, lib, primitive
, record-hasfield, sdl3, some, template-haskell, vec, vector
}:
mkDerivation {
  pname = "sdl3-bindgen-sys";
  version = "0.0.0.1";
  sha256 = "4b479a86f6af8fd43a405ad802486cb829c75ac5887e63c296f463f2c7f7de48";
  libraryHaskellDepends = [
    base bytestring containers fin primitive record-hasfield some
    template-haskell vec vector
  ];
  libraryPkgconfigDepends = [ sdl3 ];
  doHaddock = false;
  homepage = "https://github.com/jtnuttall/lithon#readme";
  description = "Complete SDL3 bindings, raw + curated, generated by hs-bindgen";
  license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
}
