{ mkDerivation, aeson, base, base64-bytestring, bytestring, lib
, text, time
}:
mkDerivation {
  pname = "typed-wire-utils";
  version = "0.2.0.0";
  sha256 = "4d40b4dcb3e3c2482bf7ae1633d9ff68073e640a5a9e2b561ef989369b6faf6c";
  libraryHaskellDepends = [
    aeson base base64-bytestring bytestring text time
  ];
  homepage = "http://github.com/typed-wire/hs-typed-wire-utils#readme";
  description = "Haskell utility library required for code generated by typed-wire compiler";
  license = lib.licenses.bsd3;
}
