{ mkDerivation, array, base, bytestring, half, lib, monad-control
, mtl, text, transformers-base
}:
mkDerivation {
  pname = "futhask-base";
  version = "0.2.0.0";
  sha256 = "de2b0d412f00af97608b85f8246f3128c15754723062be5e3996a8e3b9d379af";
  libraryHaskellDepends = [
    array base bytestring half monad-control mtl text transformers-base
  ];
  homepage = "https://gitlab.com/Gusten_Isfeldt/futhask#readme";
  description = "Base library for libraries generated by futhask";
  license = lib.licenses.bsd3;
}
