{ mkDerivation, base, bytestring, containers, glib, lib, text }:
mkDerivation {
  pname = "haskell-gi-base";
  version = "0.17";
  sha256 = "fba8d755d1772cd0e01f7e8e7ac939d5bde9646d6493516c561484853ff77b76";
  revision = "1";
  editedCabalFile = "179r13ffb9631sbjz1iiamd9g164ivj0diwjgfq1ww23i0zdc3yd";
  libraryHaskellDepends = [ base bytestring containers text ];
  libraryPkgconfigDepends = [ glib ];
  homepage = "https://github.com/haskell-gi/haskell-gi-base";
  description = "Foundation for libraries generated by haskell-gi";
  license = lib.licenses.lgpl21Only;
}
