{ mkDerivation, base, bytestring, containers, glib, lib, text }:
mkDerivation {
  pname = "haskell-gi-base";
  version = "0.20";
  sha256 = "d62e8b11d67441974e7cb52b0a30e7a1efe6051ddde62c48fe276185c670b80a";
  revision = "1";
  editedCabalFile = "00ngzzzamxkgy50i0832a0l1c8dn1473f8n5v95gyaa823fmnn7h";
  libraryHaskellDepends = [ base bytestring containers text ];
  libraryPkgconfigDepends = [ glib ];
  homepage = "https://github.com/haskell-gi/haskell-gi-base";
  description = "Foundation for libraries generated by haskell-gi";
  license = lib.licenses.lgpl21Only;
}
