{ mkDerivation, base, bytestring, containers, glib, lib, text }:
mkDerivation {
  pname = "haskell-gi-base";
  version = "0.18.1";
  sha256 = "ab6c31a6dca1bd0f7cbf4e51225dd18ef25185f70c2f33fd207968b44157b028";
  revision = "1";
  editedCabalFile = "0c26b62rr1fzw5zzjhijp1iyja2b5d7r2dggajjw2mhia05zqr8n";
  libraryHaskellDepends = [ base bytestring containers text ];
  libraryPkgconfigDepends = [ glib ];
  homepage = "https://github.com/haskell-gi/haskell-gi-base";
  description = "Foundation for libraries generated by haskell-gi";
  license = lib.licenses.lgpl21Only;
}
