{ mkDerivation, base, bytestring, containers, glib, lib, text }:
mkDerivation {
  pname = "haskell-gi-base";
  version = "0.18.4";
  sha256 = "45fb9bd2b65668d09f0643c3e4e0629df27610dfb501049c4a4b14a5edba8e16";
  revision = "1";
  editedCabalFile = "0mx64adp9fxvs5l4nzvvg2l5hm2r5dl3pcaazqna4fcymqinvgad";
  libraryHaskellDepends = [ base bytestring containers text ];
  libraryPkgconfigDepends = [ glib ];
  homepage = "https://github.com/haskell-gi/haskell-gi-base";
  description = "Foundation for libraries generated by haskell-gi";
  license = lib.licenses.lgpl21Only;
}
