{ mkDerivation, base, casadi, casadi-bindings-internal, containers
, lib, vector
}:
mkDerivation {
  pname = "casadi-bindings-core";
  version = "3.0.0.0";
  sha256 = "8cd59ae975cc1de7db78ac59f6212f2523bdf723a782a9ce0c0b47922fdf31be";
  libraryHaskellDepends = [
    base casadi-bindings-internal containers vector
  ];
  libraryPkgconfigDepends = [ casadi ];
  description = "autogenerated low level bindings to casadi";
  license = lib.licenses.lgpl3Only;
}
