{ mkDerivation, aterm, base, lib, mtl, transformers, wl-pprint }:
mkDerivation {
  pname = "aterm-utils";
  version = "0.2.0.0";
  sha256 = "3fb21c7753c5edcc8a82581b25ddefd9495563877f136e950410c62f5984999f";
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [ aterm base mtl transformers wl-pprint ];
  executableHaskellDepends = [ aterm base transformers wl-pprint ];
  homepage = "https://github.com/GaloisInc/aterm-utils";
  description = "Utility functions for working with aterms as generated by Minitermite";
  license = lib.licenses.bsd3;
  mainProgram = "ppaterm";
}
