{ mkDerivation, base, casadi, casadi-bindings-internal, containers
, lib, vector
}:
mkDerivation {
  pname = "casadi-bindings-core";
  version = "3.4.5.0";
  sha256 = "3437eacca61bc4b96f8bdf560ea3a73c2178df8d13fb21cad94081519fc91f47";
  libraryHaskellDepends = [
    base casadi-bindings-internal containers vector
  ];
  librarySystemDepends = [ casadi ];
  description = "autogenerated low level bindings to casadi";
  license = lib.licenses.lgpl3Only;
}
