{ mkDerivation, base, casadi, casadi-bindings-internal, containers
, lib, vector
}:
mkDerivation {
  pname = "casadi-bindings-core";
  version = "3.1.0.0";
  sha256 = "360f2cd21f2cb418b56b9a487333b1d18dbc86def6ab659a3061080b1194e623";
  libraryHaskellDepends = [
    base casadi-bindings-internal containers vector
  ];
  librarySystemDepends = [ casadi ];
  description = "autogenerated low level bindings to casadi";
  license = lib.licenses.lgpl3Only;
}
