{ mkDerivation, base, bytestring, containers, glib, lib, text }:
mkDerivation {
  pname = "haskell-gi-base";
  version = "0.16";
  sha256 = "1ef2d2facafdb927ee318053e43b63dceea2a0638b05a01e1e7e7f54081772f7";
  revision = "1";
  editedCabalFile = "0s6qj9zpy5g026g1azzb2p13y2z82q7c478jqs0alz84pj5v3dyl";
  libraryHaskellDepends = [ base bytestring containers text ];
  libraryPkgconfigDepends = [ glib ];
  homepage = "https://github.com/haskell-gi/haskell-gi-base";
  description = "Foundation for libraries generated by haskell-gi";
  license = lib.licenses.lgpl21Only;
}
