{ mkDerivation, base, containers, data-reify, lib }:
mkDerivation {
  pname = "data-reify-cse";
  version = "0.0.1";
  sha256 = "a04323377d040672b7a3ba519ffc32db41426257ddc594aed4511acc13bea153";
  libraryHaskellDepends = [ base containers data-reify ];
  description = "Common Sub-Expression Elimination for graphs generated by Data.Reify.";
  license = lib.licenses.bsd3;
}
