{ mkDerivation, base, containers, data-reify, lib }:
mkDerivation {
  pname = "data-reify-cse";
  version = "0.0.3";
  sha256 = "59186a2290a630d53fb2d796d9cca1260dbd70fa414814778e1cab0aeeba4e6e";
  libraryHaskellDepends = [ base containers data-reify ];
  description = "Common Sub-Expression Elimination for graphs generated by Data.Reify.";
  license = lib.licenses.bsd3;
}
