{ mkDerivation, base, casadi, casadi-bindings-internal, lib, vector
}:
mkDerivation {
  pname = "casadi-bindings-core";
  version = "2.2.0.2";
  sha256 = "6acf52b592b697f903d6324ea4d8bb3ac2e6b30722a18ad7e9bf5856bf44ffb2";
  libraryHaskellDepends = [ base casadi-bindings-internal vector ];
  libraryPkgconfigDepends = [ casadi ];
  description = "autogenerated low level bindings to casadi";
  license = lib.licenses.lgpl3Only;
}
