{ mkDerivation, base, bytestring, containers, glib, lib, text }:
mkDerivation {
  pname = "haskell-gi-base";
  version = "0.10.1";
  sha256 = "04457204453324cb8cea89d86159153bc9c141d8371212c49fa379aa06f7cde0";
  libraryHaskellDepends = [ base bytestring containers text ];
  libraryPkgconfigDepends = [ glib ];
  homepage = "https://github.com/haskell-gi/haskell-gi-base";
  description = "Foundation for libraries generated by haskell-gi";
  license = lib.licenses.lgpl21Only;
}
