{ mkDerivation, base, bytestring, containers, lib, primitive
, QuickCheck, record-hasfield, tasty, tasty-expected-failure
, tasty-hunit, tasty-quickcheck, template-haskell, transformers
, vector
}:
mkDerivation {
  pname = "hs-bindgen-runtime";
  version = "1.0.0.0";
  sha256 = "a2f3d44fe6f131b4d927d186d8e2944130ed80d769c183ccc58ac175fc9e2e6d";
  libraryHaskellDepends = [
    base bytestring containers primitive record-hasfield
    template-haskell vector
  ];
  testHaskellDepends = [
    base primitive QuickCheck tasty tasty-expected-failure tasty-hunit
    tasty-quickcheck transformers
  ];
  description = "Runtime support for code generated by hs-bindgen";
  license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
}
