{ mkDerivation, base, bytestring, containers, glib, lib, text }:
mkDerivation {
  pname = "haskell-gi-base";
  version = "0.18.2";
  sha256 = "245b17ab5769fc413f7d10b24ca57efb97962dc7debd6188d3a879454077daa1";
  revision = "1";
  editedCabalFile = "1i0jakziraqv4h5pmzbfw78c7ahxw66fgk2kh47wjn7x5c03cdjn";
  libraryHaskellDepends = [ base bytestring containers text ];
  libraryPkgconfigDepends = [ glib ];
  homepage = "https://github.com/haskell-gi/haskell-gi-base";
  description = "Foundation for libraries generated by haskell-gi";
  license = lib.licenses.lgpl21Only;
}
