{ mkDerivation, base, casadi, casadi-bindings-internal, lib, vector
}:
mkDerivation {
  pname = "casadi-bindings-core";
  version = "2.2.0.1";
  sha256 = "c150d03a90e47bc04d0a49c0644d1cb16512210813832ab903c9eec0d58dba59";
  libraryHaskellDepends = [ base casadi-bindings-internal vector ];
  libraryPkgconfigDepends = [ casadi ];
  description = "autogenerated low level bindings to casadi";
  license = lib.licenses.lgpl3Only;
}
