{ mkDerivation, base, binary, bytestring, containers, directory
, filepath, ghc-events, lib, mtl, pretty, process, unix
}:
mkDerivation {
  pname = "linux-perf";
  version = "0.3";
  sha256 = "2114d462f25efbc01c04d5ee8984b74bf3c677fc2e926b33d74e70bc9e9253a1";
  isLibrary = true;
  isExecutable = true;
  enableSeparateDataOutput = true;
  libraryHaskellDepends = [
    base binary bytestring containers mtl pretty
  ];
  executableHaskellDepends = [
    base bytestring containers directory filepath ghc-events process
    unix
  ];
  homepage = "https://github.com/bjpop/haskell-linux-perf";
  description = "Read files generated by perf on Linux";
  license = lib.licenses.bsd3;
}
