
name: "Update all-cabal-nixes"

on:
  schedule:
    # * is a special character in YAML so you have to quote this string.
    # Run once daily at 2:17 AM.
    - cron: '17 2 * * *'

  # Allow manually starting the GitHub Action from the browser.  This is nice for
  # testing.  You can manually start the workflow by clicking the "Run workflow" button on
  # https://github.com/all-cabal-nixes/all-cabal-nixes/actions/workflows/update-all-cabal-nixes.yml
  workflow_dispatch:
    inputs: {}

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      # Allow the workflow to commit and push to the repo.
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run ./all-cabal-nixes-tool.sh
        run: |
          # Generate all the .nix files
          nix-shell -p cabal2nix --command "./all-cabal-nixes-tool.sh"

      - name: Check in new files to master
        run: |
          # Set GitHub Actions Bot email address and user name.
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

          # If there are any new or changed files, check them in and push them to master.
          if [ -n "$(git status --porcelain --untracked-files=normal)" ]; then
            git add .
            git commit -m "update using all-cabal-hashes $(cd ../all-cabal-hashes && git rev-parse HEAD)"
            git push origin HEAD:master
          fi
