{ mkDerivation, base, casadi, casadi-bindings-internal, lib, vector
}:
mkDerivation {
  pname = "casadi-bindings-core";
  version = "2.2.0.0";
  sha256 = "f0799b4757341140763dbd5aa2be85f4e2119bd6e96df0f3a0fd9503c00eaa88";
  libraryHaskellDepends = [ base casadi-bindings-internal vector ];
  libraryPkgconfigDepends = [ casadi ];
  description = "autogenerated low level bindings to casadi";
  license = lib.licenses.lgpl3Only;
}
